/** Identifier helpers. Production identifiers are UUIDs generated by the platform or database. */

export function newId(): string {
  return crypto.randomUUID()
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export function isUuid(value: string): boolean {
  return UUID_PATTERN.test(value)
}

/** Human-friendly reference such as "ESB-7K3Q9P" derived from a UUID. */
export function shortReference(prefix: string, id: string): string {
  const alphabet = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
  const hex = id.replace(/-/g, '')
  let value = BigInt(`0x${hex.slice(0, 15)}`)
  let out = ''
  for (let i = 0; i < 6; i += 1) {
    out = alphabet[Number(value % 32n)] + out
    value /= 32n
  }
  return `${prefix}-${out}`
}
